### ISSUE TITLE
"An instance is already running" error message

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/qt_wallet#82]
https://bitsharestalk.org/index.php?topic=10727.msg164958#msg164958

**Comment by vikramrajkumar** [comment]
Another: https://bitsharestalk.org/index.php?topic=12651.msg166480#msg166480

**Comment by theoreticalbts** [comment]
The logic that throws this is in the qt client, it seems to check whether the database is already open.  The question is how to reliably detect crashes (or unexpected system shutdowns, e.g. due to power failure) that result in the database being left open (including lock file on disk).

I'm wondering if it might be possible to record the PID on startup, then on subsequent startups read the PID from the file.  If a process with the PID exists and seems to be another BitShares client instance, then we assume the lock is legit; you should yell at the user for trying to start multiple instances with the same datadir and exit.

If a process with the PID doesn't exist, then we'll assume it's a false positive (i.e. the system was shut down / rebooted without giving the client opportunity to clean up, so the DB lock file is still there) and try to work around it (I think I've seen one forum thread about this issue that suggests manually deleting the DB lock file).  We may want to give the user a warning and/or back up the wallet at the filesystem level before proceeding with the workaround, just in case we somehow end up triggering workaround when another client is actually running.

During a clean client shutdown we should delete the PID file when the database has been closed.

Getting the current PID and probing processes by PID on different OS's will not be fun.  It is relatively simple on Linux (just look in /proc/self and /proc/<pid>), but who knows about Mac, Windows and other UNIXes?  (Do we even want to attempt to support any UNIX other than Mac / Linux?)

**Comment by nathanhourt** [comment]
This error only appears when LevelDB dies trying to open the database (https://github.com/BitShares/qt_wallet/blob/master/ClientWrapper.cpp#L202). Crash detection is done earlier in the startup, and it gives a different error message (https://github.com/BitShares/qt_wallet/blob/master/ClientWrapper.cpp#L85).

**Comment by vikramrajkumar** [comment]
This was a misleading error message that could happen on any db open failure; I've changed the message and it should print out the error status provided by LevelDB now: https://github.com/BitShares/bitshares/issues/1227

If we get reports of this again; we should at least be able to see which database cannot open and the error status.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/82cdcc57fbd8552dccf28a0ca4643fb22fdc8c24

**Comment by vikramrajkumar** [comment]
For reference: https://bitsharestalk.org/index.php?topic=14670.msg190395#msg190395
